# Generated by Django 2.0 on 2018-09-07 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180907_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='name',
        ),
        migrations.AddField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Exercise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='set',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
