# Generated by Django 2.0 on 2018-09-07 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180907_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Session'),
            preserve_default=False,
        ),
    ]
