# Generated by Django 2.0 on 2018-09-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_exercise_muscle_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='notes',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
