# Generated by Django 2.1 on 2018-09-08 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180907_0221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
