# Generated by Django 2.0 on 2018-09-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='warmup',
        ),
        migrations.RemoveField(
            model_name='session',
            name='weight',
        ),
    ]
