# Generated by Django 2.1.1 on 2018-09-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180911_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='order',
        ),
        migrations.AddField(
            model_name='set',
            name='set_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
