# Generated by Django 2.0 on 2018-09-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workout',
            new_name='Exercise',
        ),
        migrations.AddField(
            model_name='set',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
